services:
  postgres:
    image: postgres:latest
    container_name: database-adpc-webserver
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adpc-webserver

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-adpc-webserver
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - adpc-webserver

  servidor:
    image: webserver/adpc:1.1
    container_name: adpc-webserver
    ports:
      - "5000:5000"
    networks:
      - adpc-webserver
    depends_on:
      - postgres
    volumes:
      - ./server-volume:/arquivos
  
volumes:
  postgres_data:

networks:
  adpc-webserver:
    driver: bridge

